// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3U9fR8HghIQQUqdBDRW_kIf1ApEkJjHs',
    appId: '1:6934870364:web:5c5de39a3f2d958c14e999',
    messagingSenderId: '6934870364',
    projectId: 'insulin-pump-a86ff',
    authDomain: 'insulin-pump-a86ff.firebaseapp.com',
    storageBucket: 'insulin-pump-a86ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxow99wz06RKGUiJxM91hCgv8J6dCi80U',
    appId: '1:6934870364:android:6db49a3a308e911614e999',
    messagingSenderId: '6934870364',
    projectId: 'insulin-pump-a86ff',
    storageBucket: 'insulin-pump-a86ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZW6bcDLhxYcZvauE-uIoRLoTbwzsp3iI',
    appId: '1:6934870364:ios:27f0e410a8b99b5e14e999',
    messagingSenderId: '6934870364',
    projectId: 'insulin-pump-a86ff',
    storageBucket: 'insulin-pump-a86ff.appspot.com',
    iosClientId:
        '6934870364-5jj97fqh845fomd0eqqo5dmcoj45b682.apps.googleusercontent.com',
    iosBundleId: 'com.example.insulinPump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZW6bcDLhxYcZvauE-uIoRLoTbwzsp3iI',
    appId: '1:6934870364:ios:27f0e410a8b99b5e14e999',
    messagingSenderId: '6934870364',
    projectId: 'insulin-pump-a86ff',
    storageBucket: 'insulin-pump-a86ff.appspot.com',
    iosClientId:
        '6934870364-5jj97fqh845fomd0eqqo5dmcoj45b682.apps.googleusercontent.com',
    iosBundleId: 'com.example.insulinPump',
  );
}
